# Generated by Django 5.0.2 on 2024-07-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('performer_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
